import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import contactsRouter from "./contacts.js";
import portfolioRouter from "./portfolio.js";
import teamRouter from "./team.js";
import leadsRouter from "./leads.js";
import statsRouter from "./stats.js";
import chatRouter from "./chat.js";
import chatSessionRouter from "./chatSession.js";
import adminChatRouter from "./adminChat.js";
import servicesRouter from "./services.js";
import toolsAuthRouter from "./toolsAuth.js";
import shortUrlsRouter from "./shortUrls.js";
import adminUsersRouter from "./adminUsers.js";
import recordingStatsRouter from "./recordingStats.js";
import advantixAiRouter from "./advantixAi.js";
import adminIntegrationsRouter from "./adminIntegrations.js";
import adminTasksRouter from "./adminTasks.js";
import adminNotificationsRouter from "./adminNotifications.js";
import warUpdateRouter from "./warUpdate.js";
import landingPageRouter from "./landingPage.js";
import landingPageProjectsRouter from "./landingPageProjects.js";
import blogRouter from "./blog.js";
import bugReportsRouter from "./bugReports.js";
import websiteAnalyticsRouter from "./websiteAnalytics.js";
import marketingReportsRouter from "./marketingReports.js";
import pushNotificationsRouter from "./pushNotifications.js";
import reengagementRouter from "./reengagement.js";
import contentPlansRouter from "./contentPlans.js";
import emailMarketingRouter from "./emailMarketing.js";
import inboxRouter from "./inbox.js";
import contestsRouter from "./contests.js";
import adminProjectsRouter from "./adminProjects.js";
import adminCustomPagesRouter from "./adminCustomPages.js";
import toolsPdfAudioRouter from "./toolsPdfAudio.js";
import toolsTtsRouter from "./toolsTts.js";
import smmRouter from "./smm.js";
import smmToolsRouter from "./smmTools.js";
import contentStudioRouter from "./contentStudio.js";
import toolPermissionsRouter from "./toolPermissions.js";
import adminPermissionsRouter, { ensureAdminPermissionsTable } from "./adminPermissions.js";
import adminToolsStatsRouter from "./adminToolsStats.js";
import adminOverviewStatsRouter from "./adminOverviewStats.js";
import advantixAssistantRouter from "./advantixAssistant.js";

const router: IRouter = Router();

ensureAdminPermissionsTable().catch(console.error);

router.use(healthRouter);
router.use(authRouter);
router.use(adminUsersRouter);
router.use(contactsRouter);
router.use(portfolioRouter);
router.use(servicesRouter);
router.use(teamRouter);
router.use(leadsRouter);
router.use(statsRouter);
router.use(chatRouter);
router.use(chatSessionRouter);
router.use(adminChatRouter);
router.use(toolsAuthRouter);
router.use(shortUrlsRouter);
router.use(recordingStatsRouter);
router.use("/ai", advantixAiRouter);
router.use(adminIntegrationsRouter);
router.use(adminTasksRouter);
router.use(adminNotificationsRouter);
router.use(blogRouter);
router.use(bugReportsRouter);
router.use(warUpdateRouter);
router.use(landingPageRouter);
router.use(landingPageProjectsRouter);
router.use(websiteAnalyticsRouter);
router.use(marketingReportsRouter);
router.use(pushNotificationsRouter);
router.use(reengagementRouter);
router.use(contentPlansRouter);
router.use(emailMarketingRouter);
router.use(inboxRouter);
router.use(contestsRouter);
router.use(adminProjectsRouter);
router.use(adminCustomPagesRouter);
router.use(toolsPdfAudioRouter);
router.use(toolsTtsRouter);
router.use(smmRouter);
router.use(smmToolsRouter);
router.use(contentStudioRouter);
router.use(toolPermissionsRouter);
router.use(adminPermissionsRouter);
router.use(adminToolsStatsRouter);
router.use(adminOverviewStatsRouter);
router.use(advantixAssistantRouter);

export default router;
