import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import contactsRouter from "./contacts.js";
import portfolioRouter from "./portfolio.js";
import teamRouter from "./team.js";
import leadsRouter from "./leads.js";
import statsRouter from "./stats.js";
import chatRouter from "./chat.js";
import chatSessionRouter from "./chatSession.js";
import adminChatRouter from "./adminChat.js";
import servicesRouter from "./services.js";
import toolsAuthRouter from "./toolsAuth.js";
import shortUrlsRouter from "./shortUrls.js";
import adminUsersRouter from "./adminUsers.js";
import recordingStatsRouter from "./recordingStats.js";
import advantixAiRouter from "./advantixAi.js";
import adminIntegrationsRouter from "./adminIntegrations.js";
import adminTasksRouter from "./adminTasks.js";
import adminNotificationsRouter from "./adminNotifications.js";
import warUpdateRouter from "./warUpdate.js";
import landingPageRouter from "./landingPage.js";
import landingPageProjectsRouter from "./landingPageProjects.js";
import blogRouter from "./blog.js";
import bugReportsRouter from "./bugReports.js";
import websiteAnalyticsRouter from "./websiteAnalytics.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminUsersRouter);
router.use(contactsRouter);
router.use(portfolioRouter);
router.use(servicesRouter);
router.use(teamRouter);
router.use(leadsRouter);
router.use(statsRouter);
router.use(chatRouter);
router.use(chatSessionRouter);
router.use(adminChatRouter);
router.use(toolsAuthRouter);
router.use(shortUrlsRouter);
router.use(recordingStatsRouter);
router.use("/ai", advantixAiRouter);
router.use(adminIntegrationsRouter);
router.use(adminTasksRouter);
router.use(adminNotificationsRouter);
router.use(blogRouter);
router.use(bugReportsRouter);
router.use(warUpdateRouter);
router.use(landingPageRouter);
router.use(landingPageProjectsRouter);
router.use(websiteAnalyticsRouter);

export default router;
